import { Setting } from './setting';

const TOOL = 'Argon';

type ArgonEntry = Omit<Setting, 'tool'>;

const ENTRIES: ArgonEntry[] = [
    {
        key: 'argon.host',
        category: 'Server',
        label: 'Host',
        type: 'string',
        default: 'localhost',
        description: 'Default server host name.',
    },
    {
        key: 'argon.port',
        category: 'Server',
        label: 'Port',
        type: 'number',
        default: 8000,
        description: 'Default server port number.',
    },
    {
        key: 'argon.scan_ports',
        category: 'Server',
        label: 'Scan Ports',
        type: 'boolean',
        default: true,
        description: 'Scan for the first available port if the selected one is in use.',
    },
    {
        key: 'argon.run_async',
        category: 'Server',
        label: 'Run Async',
        type: 'boolean',
        default: false,
        description: 'Run Argon asynchronously, freeing up the terminal.',
    },

    {
        key: 'argon.template',
        category: 'Project',
        label: 'Template',
        type: 'string',
        default: 'place',
        description: 'Default project template (place, model, etc.).',
    },
    {
        key: 'argon.license',
        category: 'Project',
        label: 'License',
        type: 'string',
        default: 'Apache-2.0',
        description: 'Default project license (SPDX identifier).',
    },
    {
        key: 'argon.include_docs',
        category: 'Project',
        label: 'Include Docs',
        type: 'boolean',
        default: false,
        description: 'Include documentation in the project (README, CHANGELOG, etc.).',
    },
    {
        key: 'argon.use_git',
        category: 'Project',
        label: 'Use Git',
        type: 'boolean',
        default: true,
        description: 'Use Git for source control.',
    },
    {
        key: 'argon.use_wally',
        category: 'Project',
        label: 'Use Wally',
        type: 'boolean',
        default: false,
        description: 'Use Wally for package management.',
    },
    {
        key: 'argon.use_selene',
        category: 'Project',
        label: 'Use Selene',
        type: 'boolean',
        default: false,
        description: 'Use selene for codebase linting.',
    },
    {
        key: 'argon.detect_project',
        category: 'Project',
        label: 'Detect Project',
        type: 'boolean',
        default: true,
        description: 'Automatically detect project type.',
    },

    {
        key: 'argon.rename_instances',
        category: 'Sync',
        label: 'Rename Instances',
        type: 'boolean',
        default: true,
        description: 'Automatically rename corrupted instances when syncing back.',
    },
    {
        key: 'argon.keep_duplicates',
        category: 'Sync',
        label: 'Keep Duplicates',
        type: 'boolean',
        default: false,
        description: 'Keep duplicate instances (by adding UUID suffixes) when syncing back.',
    },
    {
        key: 'argon.move_to_bin',
        category: 'Sync',
        label: 'Move To Bin',
        type: 'boolean',
        default: false,
        description: 'Move files to the bin instead of deleting them (two-way sync).',
    },
    {
        key: 'argon.changes_threshold',
        category: 'Sync',
        label: 'Changes Threshold',
        type: 'number',
        default: 5,
        description: 'Number of changes allowed before prompting for confirmation.',
    },
    {
        key: 'argon.max_unsynced_changes',
        category: 'Sync',
        label: 'Max Unsynced Changes',
        type: 'number',
        default: 10,
        description: 'Maximum number of unsynced changes before showing a warning.',
    },
    {
        key: 'argon.ignore_line_endings',
        category: 'Sync',
        label: 'Ignore Line Endings',
        type: 'boolean',
        default: true,
        description: 'Ignore line endings when reading files to avoid script diffs.',
    },
    {
        key: 'argon.with_sourcemap',
        category: 'Sync',
        label: 'With Sourcemap',
        type: 'boolean',
        default: false,
        description: 'Always run commands with sourcemap generation.',
    },
    {
        key: 'argon.smart_paths',
        category: 'Sync',
        label: 'Smart Paths',
        type: 'boolean',
        default: false,
        description: 'Use the smart path resolver when running commands.',
    },
    {
        key: 'argon.build_xml',
        category: 'Sync',
        label: 'Build XML',
        type: 'boolean',
        default: false,
        description: 'Build using XML format by default.',
    },

    {
        key: 'argon.rojo_mode',
        category: 'Language',
        label: 'Rojo Mode',
        type: 'boolean',
        default: true,
        description: 'Use the Rojo namespace by default.',
    },
    {
        key: 'argon.ts_mode',
        category: 'Language',
        label: 'TypeScript Mode',
        type: 'boolean',
        default: false,
        description: 'Use roblox-ts by default.',
    },
    {
        key: 'argon.lua_extension',
        category: 'Language',
        label: 'Lua Extension',
        type: 'boolean',
        default: false,
        description: 'Use the .lua file extension instead of .luau when writing scripts.',
    },
    {
        key: 'argon.package_manager',
        category: 'Language',
        label: 'Package Manager',
        type: 'string',
        default: 'npm',
        enum: ['npm', 'bun', 'pnpm', 'yarn'],
        description: 'Package manager to use when running roblox-ts scripts.',
    },

    {
        key: 'argon.check_updates',
        category: 'Updates',
        label: 'Check Updates',
        type: 'boolean',
        default: true,
        description: 'Check for new Argon releases on startup.',
    },
    {
        key: 'argon.auto_update',
        category: 'Updates',
        label: 'Auto Update',
        type: 'boolean',
        default: false,
        description: 'Automatically install Argon updates if available.',
    },
    {
        key: 'argon.install_plugin',
        category: 'Updates',
        label: 'Install Plugin',
        type: 'boolean',
        default: true,
        description: 'Install the Roblox plugin locally and keep it updated.',
    },
    {
        key: 'argon.update_templates',
        category: 'Updates',
        label: 'Update Templates',
        type: 'boolean',
        default: true,
        description: 'Update default project templates when available.',
    },

    {
        key: 'argon.share_stats',
        category: 'Privacy',
        label: 'Share Stats',
        type: 'boolean',
        default: true,
        description: 'Share anonymous Argon usage statistics with the community.',
    },
];

export const ARGON_SETTINGS: Setting[] = ENTRIES.map((entry) => ({ ...entry, tool: TOOL }));
