import { Setting } from './setting';

// User-facing editor settings. Applied live by monaco-editor.component.ts on
// top of the base EDITOR_OPTIONS (see code-editor/editor-settings.ts), so
// changing one updates open editors immediately.
export const EDITOR_SETTINGS: Setting[] = [
    {
        key: 'lunar.editor.fontSize',
        tool: 'Editor',
        category: 'Text',
        label: 'Font size',
        type: 'number',
        default: 13,
        min: 8,
        max: 32,
        description: 'Editor font size, in pixels.',
    },
    {
        key: 'lunar.editor.fontFamily',
        tool: 'Editor',
        category: 'Text',
        label: 'Font family',
        type: 'string',
        default: "'JetBrains Mono', monospace",
        description: 'Editor font family. Falls back to a monospace font.',
    },
    {
        key: 'lunar.editor.fontLigatures',
        tool: 'Editor',
        category: 'Text',
        label: 'Font ligatures',
        type: 'boolean',
        default: true,
        description: 'Render programming ligatures (e.g. -> or ~=) when the font supports them.',
    },
    {
        key: 'lunar.editor.autoSave',
        tool: 'Editor',
        category: 'Text',
        label: 'Auto save',
        type: 'boolean',
        default: true,
        description: 'Save a file to disk automatically after you stop typing.',
    },
    {
        key: 'lunar.editor.autoSaveDelay',
        tool: 'Editor',
        category: 'Text',
        label: 'Auto save delay (seconds)',
        type: 'number',
        default: 1,
        min: 0.2,
        max: 10,
        description: 'How long to wait after your last keystroke before auto-saving.',
    },
    {
        key: 'lunar.editor.tabSize',
        tool: 'Editor',
        category: 'Text',
        label: 'Tab size',
        type: 'number',
        default: 4,
        min: 1,
        max: 8,
        description: 'Number of spaces a tab is rendered as.',
    },
    {
        key: 'lunar.editor.wordWrap',
        tool: 'Editor',
        category: 'Text',
        label: 'Word wrap',
        type: 'string',
        default: 'off',
        enum: ['off', 'on'],
        description: 'Wrap long lines instead of scrolling horizontally.',
    },
    {
        key: 'lunar.editor.lineNumbers',
        tool: 'Editor',
        category: 'Display',
        label: 'Line numbers',
        type: 'string',
        default: 'on',
        enum: ['on', 'off', 'relative'],
        description: 'How line numbers are shown in the gutter.',
    },
    {
        key: 'lunar.editor.minimap',
        tool: 'Editor',
        category: 'Display',
        label: 'Minimap',
        type: 'boolean',
        default: false,
        description: 'Show the code minimap on the right edge.',
    },
    {
        key: 'lunar.editor.stickyScroll',
        tool: 'Editor',
        category: 'Display',
        label: 'Sticky scroll',
        type: 'boolean',
        default: false,
        description: 'Pin the enclosing scope (function/block) to the top while scrolling.',
    },
    {
        key: 'lunar.editor.renderWhitespace',
        tool: 'Editor',
        category: 'Display',
        label: 'Render whitespace',
        type: 'string',
        default: 'selection',
        enum: ['none', 'boundary', 'selection', 'all'],
        description: 'When to draw whitespace characters (spaces/tabs).',
    },
    {
        key: 'lunar.diagnostics.hideUnused',
        tool: 'Editor',
        category: 'Diagnostics',
        label: 'Hide unused-variable warnings',
        type: 'boolean',
        default: false,
        description: "Suppress Luau 'never used' lints (LocalUnused, FunctionUnused, ImportUnused) for unused variables, functions, and imports.",
    },
    {
        key: 'lunar.checkForUpdates',
        tool: 'Editor',
        category: 'Updates',
        label: 'Check for updates',
        type: 'boolean',
        default: true,
        description: 'On startup, check GitHub for a newer Lunar release and offer to download it.',
    },
];
